// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1Ow48gbfO80Oq_mfDRlCMwWfamxPptEQ',
    appId: '1:976000516991:web:fcdb0685b40e14f5fd904a',
    messagingSenderId: '976000516991',
    projectId: 'givit-16129',
    authDomain: 'givit-16129.firebaseapp.com',
    storageBucket: 'givit-16129.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5xHOaLVUtr7fKXR7Uvv7Y9wOuQx1EcJg',
    appId: '1:976000516991:android:b31143e7cf1990e3fd904a',
    messagingSenderId: '976000516991',
    projectId: 'givit-16129',
    storageBucket: 'givit-16129.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVMCvfI_Ot-njAtXEL9qe7ela0xF3ZtLc',
    appId: '1:976000516991:ios:2a10ae27d239ca30fd904a',
    messagingSenderId: '976000516991',
    projectId: 'givit-16129',
    storageBucket: 'givit-16129.appspot.com',
    iosClientId: '976000516991-cqbn2jovec2mpf7a4md0mpct1qaun6he.apps.googleusercontent.com',
    iosBundleId: 'com.givit.givit',
  );
}
